### ISSUE TITLE
readln can fail

### ISSUE THREAD

**Issue by adriesse** [ssproessig/Python-PS2000B#2]
https://github.com/ssproessig/Python-PS2000B/blob/3d27c634c91acb2da84c0fe3cc733077560672ce/pyps2000b/PS2000B.py#L233

Readln will return prematurely if the telegram contains a newline and/or carriage return.

Use ```serial.read(99)``` and rely on the port's timeout parameter to stop reading.

**Comment by ssproessig** [comment]
will do - thanks for mentioning
